TRUNCATE TABLE product RESTART IDENTITY CASCADE;

INSERT INTO product (name, price, description, image_url, category)
VALUES ('Logitech G Pro X', 129.99, 'Mechanical gaming keyboard with swappable switches.',
        'https://example.com/keyboard1.jpg', 'Keyboard'),
       ('Razer BlackWidow V4', 159.99, 'RGB mechanical keyboard with green switches.',
        'https://example.com/keyboard2.jpg', 'Keyboard'),
       ('SteelSeries Apex 7', 139.99, 'OLED display and durable aluminum frame.', 'https://example.com/keyboard3.jpg',
        'Keyboard'),
       ('Corsair K70 RGB MK.2', 149.99, 'Full-size mechanical keyboard with per-key lighting.',
        'https://example.com/keyboard4.jpg', 'Keyboard'),
       ('Logitech G502 HERO', 89.99, 'High-performance gaming mouse with 11 buttons.', 'https://example.com/mouse1.jpg',
        'Mouse'),
       ('Razer DeathAdder V3', 79.99, 'Ergonomic optical mouse with precise tracking.',
        'https://example.com/mouse2.jpg', 'Mouse'),
       ('SteelSeries Rival 5', 69.99, 'Multi-genre mouse with 9 programmable buttons.',
        'https://example.com/mouse3.jpg', 'Mouse'),
       ('Glorious Model O', 59.99, 'Lightweight honeycomb gaming mouse.', 'https://example.com/mouse4.jpg', 'Mouse'),
       ('HyperX Cloud II', 99.99, '7.1 surround sound gaming headset.', 'https://example.com/headset1.jpg', 'Headset'),
       ('SteelSeries Arctis Nova 7', 179.99, 'Wireless headset with dual connectivity.',
        'https://example.com/headset2.jpg', 'Headset'),
       ('Razer Kraken V3', 119.99, 'RGB wired headset with THX spatial audio.', 'https://example.com/headset3.jpg',
        'Headset'),
       ('Corsair HS80 RGB', 129.99, 'Wireless headset with Dolby Atmos support.', 'https://example.com/headset4.jpg',
        'Headset'),
       ('SteelSeries QcK Heavy', 29.99, 'Thick cloth mousepad for maximum control.',
        'https://example.com/mousepad1.jpg', 'Mousepad'),
       ('Razer Gigantus V2', 34.99, 'Soft and smooth surface for precision.', 'https://example.com/mousepad2.jpg',
        'Mousepad'),
       ('Corsair MM300', 24.99, 'Anti-fray cloth mousepad with stitched edges.', 'https://example.com/mousepad3.jpg',
        'Mousepad'),
       ('Logitech G840 XL', 49.99, 'Extra-large mousepad covering keyboard and mouse area.',
        'https://example.com/mousepad4.jpg', 'Mousepad'),
       ('Xbox Wireless Controller', 64.99, 'Ergonomic wireless controller for Xbox and PC.',
        'https://example.com/controller1.jpg', 'Controller'),
       ('PlayStation DualSense', 69.99, 'Haptic feedback and adaptive triggers.', 'https://example.com/controller2.jpg',
        'Controller'),
       ('8BitDo Pro 2', 59.99, 'Retro-style controller with modern features.', 'https://example.com/controller3.jpg',
        'Controller'),
       ('Razer Wolverine V2', 99.99, 'Wired controller with additional remappable buttons.',
        'https://example.com/controller4.jpg', 'Controller'),
       ('Secretlab TITAN Evo 2022', 499.99, 'Premium ergonomic gaming chair with memory foam.',
        'https://example.com/chair1.jpg', 'Chair'),
       ('DXRacer Formula Series', 349.99, 'Durable frame and adjustable lumbar support.',
        'https://example.com/chair2.jpg', 'Chair'),
       ('AndaSeat Kaiser 3', 449.99, 'PU leather gaming chair with magnetic head pillow.',
        'https://example.com/chair3.jpg', 'Chair'),
       ('Corsair T3 Rush', 279.99, 'Fabric-covered chair with breathable design.', 'https://example.com/chair4.jpg',
        'Chair'),
       ('Blue Yeti', 129.99, 'USB microphone with multiple pickup patterns.', 'https://example.com/mic1.jpg',
        'Microphone'),
       ('Elgato Wave:3', 149.99, 'Digital mic with built-in anti-distortion tech.', 'https://example.com/mic2.jpg',
        'Microphone'),
       ('Razer Seiren X', 99.99, 'Compact USB mic for streaming and podcasting.', 'https://example.com/mic3.jpg',
        'Microphone'),
       ('ASUS ROG Swift 27"', 599.99, '1440p gaming monitor with 165Hz refresh rate.',
        'https://example.com/monitor1.jpg', 'Monitor'),
       ('Samsung Odyssey G5', 379.99, 'Curved 32” QHD monitor with FreeSync support.',
        'https://example.com/monitor2.jpg', 'Monitor'),
       ('AOC 24G2SPU', 219.99, '1080p 165Hz monitor with slim bezels.', 'https://example.com/monitor3.jpg', 'Monitor');
